---
- hosts: all
  become: yes
  vars:
     server_name: "{{ ansible_default_ipv4.address }}"
    #document_root: /usr/share/nginx/html
    #app_root: test-nginx 
    #index_file: test.html
  vars_files: vars/values.yml
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
    - name: Config template
      template:
        src:  nginx.conf.j2
        dest: /etc/nginx/sites-available/test-nginx
      notify: Restart Nginx
    - name: Index template
      template:
        src: index.html.j2
        dest: "{{ document_root }}/{{ index_file }}"
      notify: Restart Nginx  
    - name: Enable site config
      file:
        src: /etc/nginx/sites-available/test-nginx
        dest: /etc/nginx/sites-enabled/test-nginx
        state: link
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
